{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
type: Opaque
stringData:
  DATABASE_URL: {{required (print "Please enter Postgresql URL") .Values.secret.postgresqlURL }}
  SCRAIBER_API_SECRET: {{required (print "Please enter FastAPI secret") .Values.secret.scraiberAPISecret }}
  SENDINBLUE_API_KEY: {{required (print "Please enter Sendinblue API key") .Values.secret.sendinblueAPIKey }}
  CLUSTER_DICT: {{ .Files.Get "cluster_dict.json" | toPrettyJson }}
  CONFIG_FILE: {{ .Files.Get "config" | toPrettyJson }}
{{- end }}
