{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
type: Opaque
stringData:
  DATABASE_URL: {{ required (print "Please enter Postgresql URL") .Values.secret.postgresqlURL }}
  SENDINBLUE_API_KEY: {{ required (print "Please enter Sendinblue API key") .Values.secret.sendinblueAPIKey }}
  DOMAIN_NAME: {{ required (print "Please enter a domain name") .Values.secret.domainName }}
  AUTH0_DOMAIN: {{ required (print "Please enter the Auth0 domain") .Values.secret.auth0_domain }}
  AUTH0_CLIENTID_FRONTEND: {{ required (print "Please enter the Auth0 Client ID for the frontend") .Values.secret.auth0_clientid_frontend }}
  AUTH0_CLIENTID_BACKEND: {{ required (print "Please enter the Auth0 Client ID for the backend") .Values.secret.auth0_clientid_backend }}
  AUTH0_CLIENT_SECRET_BACKEND: {{ required (print "Please enter the Auth0 Client secret for the backend") .Values.secret.auth0_client_secret_backend }}
  AUTH0_AUDIENCE: {{ required (print "Please enter the Auth0 audience") .Values.secret.auth0_audience }}
  CLUSTER_DICT: {{ .Files.Get "cluster_dict.json" | toPrettyJson }}
  CONFIG_FILE: {{ .Files.Get "config" | toPrettyJson }}
{{- end }}
