{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
type: Opaque
stringData:
  DATABASE_URL: {{required (print "Please enter Postgresql URL") .Values.secret.postgresqlURL }}
{{- end }}
