# pull official base image
FROM python:3.10.0-slim

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /usr/src/app/requirements.txt

RUN apt-get update && apt-get install -y curl\
    && pip install --upgrade pip \
    && pip install --no-cache-dir --upgrade -r /usr/src/app/requirements.txt \
    && pip install pytest==6.2.5 \
    && pip install httpx==0.21.3 \
    && pip install asgi-lifespan==1.0.1 \
    && pip install asyncio==3.4.3 \
    && pip install trio==0.19.0

# copy project
COPY . /usr/src/app/

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
